### ISSUE TITLE
Source distribution on pypi is too large

### ISSUE THREAD

**Issue by willrogers** [dls-controls/pytac#110]
See https://pypi.org/project/pytac/0.3.0/#files - the tar.gz file is 6MB.

This happened because of the line in `MANIFEST.in`:

```
recursive-include docs *
```

I just need to figure out whether to include the docs directory and if so how to filter what I need.

**Comment by T-Nicholls** [comment]
I suspect this is because the local docs build(s) were included, as the docs folder itself is very small on a fresh installation. If you do decide to include the docs you could just manually delete the `_build` folder each time, rather than having to work out how to selectively ignore it. Another option is I could implement automatic wheel building as we did for AT, it should be easier for Pytac.

**Comment by willrogers** [comment]
I don't think we need the `docs` directory in the source distribution at all. See e.g. the last comment here: https://stackoverflow.com/questions/24727709/do-python-projects-need-a-manifest-in-and-what-should-be-in-it
